#!/usr/bin/env python3
"""
Generates src/lib/generated/*.ts from the Python project's own field maps
(../python/fields_ffx.py, ../python/fields_ffx2.py) - the Python source
stays the single source of truth; this keeps the TypeScript port exactly
in sync with it instead of a hand-transcribed (and driftable) copy. Re-run
this whenever the Python field maps change.

Run from typescript/:  python3 gen_fields.py
"""

import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "python"))

from fields_ffx import FFX_CHECKPOINTS, FFX_FIELDS  # noqa: E402
from fields_ffx2 import FFX2_FIELDS  # noqa: E402

OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "src", "lib", "generated")
os.makedirs(OUT_DIR, exist_ok=True)


def field_to_json(f):
    d = {"name": f.name, "offset": f.offset, "kind": f.kind}
    if f.bit is not None:
        d["bit"] = f.bit
    if f.note:
        d["note"] = f.note
    return d


def write_fields_ts(filename, const_name, fields):
    rows = [field_to_json(f) for f in fields]
    path = os.path.join(OUT_DIR, filename)
    with open(path, "w", encoding="utf-8") as out:
        out.write(
            "// AUTO-GENERATED by typescript/gen_fields.py from the Python project's "
            f"{const_name.lower()} field map. Do not hand-edit - re-run the "
            "generator instead.\n\n"
        )
        out.write('import type { FieldDef } from "../fields";\n\n')
        # Parsed from a JSON string at runtime, not a typed array literal -
        # TypeScript's checker chokes ("union type too complex") trying to
        # structurally verify thousands of object literals against FieldDef
        # inline; JSON.parse sidesteps that while staying just as correct,
        # since this data is already Python-verified before being written.
        out.write(f"const {const_name}_JSON =\n  '")
        out.write(json.dumps(rows, separators=(",", ":")).replace("\\", "\\\\").replace("'", "\\'"))
        out.write("';\n\n")
        out.write(f"export const {const_name}: FieldDef[] = JSON.parse({const_name}_JSON);\n")
    print(f"wrote {path} ({len(rows)} fields)")


def write_checkpoints_ts():
    rows = [
        {"label": label, "room": room, "spawn": spawn, "progress": progress, "note": note}
        for label, room, spawn, progress, note in FFX_CHECKPOINTS
    ]
    path = os.path.join(OUT_DIR, "checkpoints.ts")
    with open(path, "w", encoding="utf-8") as out:
        out.write(
            "// AUTO-GENERATED by typescript/gen_fields.py from the Python project's "
            "FFX_CHECKPOINTS. Do not hand-edit - re-run the generator instead.\n\n"
        )
        out.write("export interface Checkpoint {\n")
        out.write("  label: string;\n  room: number;\n  spawn: number;\n")
        out.write("  progress: number | null;\n  note: string;\n}\n\n")
        out.write("export const FFX_CHECKPOINTS: Checkpoint[] = ")
        out.write(json.dumps(rows, separators=(",", ":")))
        out.write(";\n")
    print(f"wrote {path} ({len(rows)} checkpoints)")


write_fields_ts("fieldsFfx.ts", "FFX_FIELDS", FFX_FIELDS)
write_fields_ts("fieldsFfx2.ts", "FFX2_FIELDS", FFX2_FIELDS)
write_checkpoints_ts()
