"""
FFX2 story/dialogue flag data.

Extracted (via a small regex parser, not hand-transcribed) from
Meth962/FFX2SaveEditor's Models/GameInfo.cs (GameInfo.Flags +
GameInfo.Requisites - both use the same StoryFlag(address, bitmask,
description, chapter, location[, faction], requisite) shape, so they're
merged here into one list; the 14 'Requisites' entries are flagged
via is_requisite=True).

Each entry is ONE BIT in the 16KB (0x4000-byte) story-flag region that
starts at save-body offset 0x222C (see Ffx2Save.cs: storyOffset=0x222c,
StoryFlagBytes=new byte[0x4000], and byte i of that region lives at
absolute body offset storyOffset + i). address below is relative to
that region (i.e. real body offset = STORY_FLAG_BASE + address), bit
is 0-7 within that byte.

Not independently byte-verified against a real save (unlike checksum.py) -
read straight off working, actively-maintained editor source, same trust
level as the rest of fields_ffx2.py.

One upstream entry was dropped: address 0x709 had bitmask 0x05 in the original C# source, which
isn't a single power-of-two bit (can't be a simple flag) - looks like a typo
upstream, so it's excluded rather than guessed at.
"""

STORY_FLAG_BASE = 0x222C

# (address, bit, description, chapter, location, is_requisite)
STORY_FLAGS = [
    (0x19, 2, 'Rikku: Hey, give it back already!', 1, 'Intro Mission', False),
    (0x19, 7, '????: Sorry, no time for an encore!', 1, 'Intro Mission', False),
    (0x25, 5, 'Rikku: Hold still!', 1, 'Intro Mission', False),
    (0x32, 1, 'Rikku: Hey, you run too fast!', 1, 'Intro Mission', False),
    (0x32, 2, "????: You're too slow, little girl.", 1, 'Intro Mission', False),
    (0x33, 6, "????: That's quite enough sniveling, boys.", 1, 'Intro Mission', False),
    (0x34, 5, "Leblanc: But it won't be yours for long, loves!", 1, 'Intro Mission', False),
    (0x34, 6, "Leblanc: I won't let you off so easily next time!", 1, 'Intro Mission', False),
    (0x4b, 1, 'Rikku: You sure look like you were enjoying yourself.', 1, 'Airship After Intro Mission', False),
    (0x57, 5, 'Intro to Rikku', 1, 'Airship After Intro Mission', False),
    (0x58, 7, 'Intro to Paine', 1, 'Airship After Intro Mission', False),
    (0x59, 5, 'Intro to Brother', 1, 'Airship After Intro Mission', False),
    (0x59, 7, 'Intro to Brother 2', 1, 'Airship After Intro Mission', False),
    (0x5a, 6, 'Intro to Shin', 1, 'Airship After Intro Mission', False),
    (0x5a, 7, 'Intro to Barkeep', 1, 'Airship After Intro Mission', False),
    (0x1dd5, 5, 'Watched Treasure Sphere #1', 1, 'Airship After Intro Mission', False),
    (0x64, 1, 'Buddy: Treasure sphere waves at Gagazete.', 1, 'Airship After Intro Mission', False),
    (0x7d, 1, "Yuna's intro to Gagazete mission.", 1, 'Gagazete', False),
    (0xbb, 5, 'Paine&Rikku: Yuna!', 1, 'Gagazete', False),
    (0xd4, 5, "Rikku: We're not getting across this way.", 1, 'Gagazete', False),
    (0xed, 5, 'Brother: What happened? Is Yuna okay?', 1, 'Gagazete', False),
    (0xfa, 3, 'Leblanc: Er, Leblanc. Remember that name well, loves!', 1, 'Gagazete', False),
    (0xfc, 1, 'Leblanc: And this is the thanks I get for going easy on you.', 1, 'Gagazete', False),
    (0x113, 1, 'Logos: You look a tad flushed. Why not stop to catch your breath!', 1, 'Gagazete', False),
    (0x11f, 5, 'Leblanc: You know how I hate the damp!', 1, 'Gagazete', False),
    (0x12c, 1, "Ormi: Let's show the ladies a nice, warm welcome!", 1, 'Gagazete', False),
    (0x138, 5, 'Leblanc: Would-Would you, would you stop staring!', 1, 'Gagazete', False),
    (0x145, 4, "Rikku: It figures we'd run into something like this.", 1, 'Gagazete', False),
    (0x151, 6, "Leblanc: It's obvious to the trained eye. That sphere's just a dud.", 1, 'Gagazete', False),
    (0x15e, 1, 'Rikku: Brother, mission complete!', 1, 'Gagazete', False),
    (0x4ee, 5, 'Buddy: He said something about Yuna being in trouble, then he just jumped ship.', 1, 'Airship After Mission 1', False),
    (0x4fb, 3, 'Yuna: Thank you, Brother.', 1, 'Airship After Mission 1', False),
    (0x507, 6, "Yuna: Think it's worth anything? (Speak to Shinra to watch sphere)", 1, 'Airship After Mission 1', False),
    (0x5e8, 5, "Yuna's intro to Kilika", 1, 'Kilika', False),
    (0x5f5, 1, 'Barthello: Dona!', 1, 'Kilika', False),
    (0x601, 5, 'Dona: Well, look who we have here.', 1, 'Kilika', False),
    (0x93b, 1, "Yuna: I couldn't bring myself to tell them it was just an impostor.", 1, 'Luca', False),
    (0x947, 1, 'Yuna: Believe it or not, this was the easy part!', 1, 'Luca', False),
    (0x954, 7, 'Yuna: The plan was to sneak into the concert, and recover the garment grid.', 1, 'Luca', False),
    (0x96d, 3, "Yuna: Did I do it because I couldn't turn him down,...", 1, 'Luca', False),
    (0x992, 1, "Yuna: It's me!", 1, 'Luca', False),
    (0x992, 4, 'Yuna: Rikku sure was having fun (must have talked to yuna as moogle)', 1, 'Luca', False),
    (0x9ab, 7, 'Yuna: So, this is my life now.', 1, 'Luca', False),
    (0x9b7, 5, 'Rin: Ah, the lady Yuna.', 1, 'Luca', False),
    (0x60e, 1, "Yuna does intro to Mi'ihen", 1, "Mi'ihen Highroad", False),
    (0x61a, 5, "Rikku: It's those creeps again!", 1, 'Mushroom Rock Road', False),
    (0x627, 1, '????: Good to see you again, Lady Yuna!', 1, 'Mushroom Rock Road', False),
    (0x62a, 1, "Rikku: Yeah! Let's hunt some fiend! (chose 'sure we're game!')", 1, 'Mushroom Rock Road', False),
    (0x633, 5, 'Claska: *sighs*', 1, 'Mushroom Rock Road', False),
    (0x640, 1, 'Yuna: There they are!', 1, 'Mushroom Rock Road', False),
    (0x64c, 5, "Ormi: This one ain't no good?", 1, 'Mushroom Rock Road', False),
    (0x659, 1, '????: Hey. Long time no see. Remember me?', 1, 'Mushroom Rock Road', False),
    (0x67e, 5, '????: Oh, wow! Lady Yuna!', 1, 'Mushroom Rock Road', False),
    (0x665, 5, 'Yuna: This is Youth League Headquarters.', 1, 'Mushroom Rock Road', False),
    (0x672, 1, "????: It's been too long, Lady Yuna.", 1, 'Mushroom Rock Road', False),
    (0x674, 3, 'Rikku: There sure do seem to be a lot of weirdos around here.', 1, 'Mushroom Rock Road', False),
    (0x666, 1, "Maechen: Why, Lady Yuna! I believe it's been fully two years!", 1, 'Mushroom Rock Road', False),
    (0x666, 4, 'Maechen: These past two years have been truly tumultuous.', 1, 'Mushroom Rock Road', False),
    (0x667, 5, 'Maechen: The Seekers scoured Spira for ancient spheres,... (2nd iteration)', 1, 'Mushroom Rock Road', False),
    (0x668, 7, 'Maechen: The founder of the Seekers was a man by the name... (3rd iteration)', 1, 'Mushroom Rock Road', False),
    (0x669, 7, 'Maechen: New Yevon would not release its spheres. (4th iteration)', 1, 'Mushroom Rock Road', False),
    (0x66a, 3, 'Maechen: And the man who united them? (5th iteration)', 1, 'Mushroom Rock Road', False),
    (0x66b, 4, 'Maechen: Looking at all the young people gathered here to... (6th iteration)', 1, 'Mushroom Rock Road', False),
    (0x66c, 3, "Maechen: I'd like to shake your hand... (7th final)", 1, 'Mushroom Rock Road', False),
    (0x66c, 6, "Maechen: Oh, thank you. Now this old scholar can go in peace. (choose 'of course!')", 1, 'Mushroom Rock Road', False),
    (0x635, 2, 'Clasko: I want to find my place!', 1, 'Mushroom Rock Road', False),
    (0x1dbc, 7, "Let's see, total surviving... (Crimson Report 1)", 1, 'Mushroom Rock Road', False),
    (0x520, 5, "Clasko: Why won't the room stop shaking?", 1, 'Mushroom Rock Road', False),
    (0x68b, 1, "Yuna's intro to Djose Temple", 1, 'Djose Temple', False),
    (0x697, 5, "Yuna: Everyone's staring.", 1, 'Djose Temple', False),
    (0x6a4, 1, 'Gippal: E ryva ymnayto ehdanveafat three people.', 1, 'Djose Temple', False),
    (0x6a4, 6, 'Gippal: You uh here for an interview?', 1, 'Djose Temple', False),
    (0x6b0, 5, 'Gippal: Never been this close to a celebrity before.', 1, 'Djose Temple', False),
    (0x6c9, 5, "Yuna's intro to Moonflow", 1, 'Moonflow', False),
    (0x6d6, 1, "Tobli: On this spot, I'll be sponsoring...", 1, 'Moonflow', False),
    (0x73a, 1, "Yuna's intro to Guadosalam", 1, 'Guadosalam', False),
    (0x746, 5, 'Yuna: The Farplane: a place that unites the living...', 1, 'Guadosalam', False),
    (0x753, 2, 'Yuna: Guess what! Rikku finally overcame her fear...', 1, 'Thunder Plains', False),
    (0x75f, 5, "Yuna's intro to Macalania", 1, 'Macalania Woods', False),
    (0x785, 1, 'Bayra: The woods will soon be no more.', 1, 'Macalania Woods', False),
    (0x791, 5, 'Donga: The end has come faster than I thought.', 1, 'Macalania Woods', False),
    (0x79e, 1, 'Pukutak: Oh me, oh my, what did you say?', 1, 'Macalania Woods', False),
    (0x75f, 7, 'Tromell: Oh, High Summoner Yuna.', 1, 'Macalania Woods', False),
    (0x760, 4, 'Tromell: Many Ronso lost their lives at... (2nd talk)', 1, 'Macalania Woods', False),
    (0x761, 5, 'Tromell: Ah, well, what brings the high summoner...(4th talk)', 1, 'Macalania Woods', False),
    (0x7aa, 5, 'Frana es ra?', 1, 'Macalania Woods', False),
    (0x76c, 1, "Rikku: O'aka XXIII! Where are you?", 1, 'Macalania Woods', False),
    (0x778, 5, "O'aka XXIII: Hahaha!", 1, 'Macalania Woods', False),
    (0x53a, 4, "O'aka: Welcome to O'aka's. (first time speaking to him on ship)", 1, 'Macalania Woods', False),
    (0x7dc, 5, "Yuna's intro to Bikanel", 1, 'Bikanel Island', False),
    (0x80e, 5, 'Muugs mega drao yna cusehk du.', 1, 'Bikanel Island', False),
    (0x827, 5, "Nhadala: I'm busy, so make it fast okay?", 1, 'Bikanel Island', False),
    (0x840, 5, 'Nhadala: Just what we needed! (Mission complete)', 1, 'Bikanel Island', False),
    (0x7c3, 5, "Yuna's intro of Bevelle", 1, 'Bevelle', False),
    (0x7d0, 1, 'Oh! The high summoner!', 1, 'Bevelle', False),
    (0x7d1, 5, 'Baralai: A pleasure, Lady Yuna. I am Baralai.', 1, 'Bevelle', False),
    (0x859, 5, "Yuna's intro to Calm Lands", 1, 'Calm Lands', False),
    (0x866, 1, "Yuna's intro to Gagazete", 1, 'Mt Gagazete', False),
    (0x872, 6, 'Yuna look well. Kimahri glad.', 1, 'Mt Gagazete', False),
    (0x546, 1, "Yuna's intro to Besaid", 1, 'Besaid', False),
    (0x55f, 1, 'LuLu: Welcome back', 1, 'Besaid', False),
    (0x56c, 0, 'Rikku: Kimahri said he found it on Mt. Gagazete. (sphere cutscene)', 1, 'Besaid', False),
    (0x584, 6, "Yuna: Oh, where's Wakka?", 1, 'Besaid', False),
    (0x591, 1, 'Wakka: something wrong? (inside cave)', 1, 'Besaid', False),
    (0x59d, 5, 'Brother: This is Brother. You alright, Yuna?', 1, 'Besaid', False),
    (0x5aa, 1, 'Paine: Find a sphere and the fiends appear.', 1, 'Besaid', False),
    (0x5c3, 1, 'Wakka: Find anything?', 1, 'Besaid', False),
    (0x5c3, 6, 'Rikku: So, what sphere were you looking for?', 1, 'Besaid', False),
    (0x5c6, 7, "Rikku: That's right, Dad.", 1, 'Besaid', False),
    (0x5c7, 5, 'Buddy: You read me? You guys about finished down there?', 1, 'Besaid', False),
    (0x8ca, 1, "Yuna's intro to Zanarkand", 1, 'Zanarkand', False),
    (0xad6, 5, '????: Yuna?', 1, 'Zanarkand', False),
    (0x8e3, 1, '????: Taro, Hana, you ready?', 1, 'Zanarkand', False),
    (0x8ef, 5, 'Come in. Come in. Do you read me?', 1, 'Zanarkand', False),
    (0x8fc, 1, 'Rikku: Um, the clue is "monkey," right?', 1, 'Zanarkand', False),
    (0x908, 5, 'Cid: Welcome!', 1, 'Zanarkand', False),
    (0x915, 1, 'Two years ago, we cast off our beliefs here.', 1, 'Zanarkand', False),
    (0x918, 3, 'Isaaru: My job. I bring excitement to those...', 1, 'Zanarkand', False),
    (0x92e, 3, 'Paine: How about "kick...its...ass."', 1, 'Zanarkand', False),
    (0x52d, 1, 'Brother: Ehcusehk dydy! Gullwings, du ouun sdydeuhs!', 1, 'Airship', False),
    (0x898, 1, 'Rikku stumbles into scene giggling. A second before Yuna speaks.', 1, 'Kilika', False),
    (0x8a4, 5, 'Yuna: These are all sphere hunters?', 1, 'Kilika', False),
    (0x8a5, 4, 'Nooj: An important sphere is hidden in Kilika', 1, 'Kilika', False),
    (0x8bd, 5, 'Which is why I keep telling you...', 1, 'Kilika', False),
    (0x8be, 6, 'Rikku: Ha! How do you like that?', 1, 'Kilika', False),
    (0x9d0, 5, 'Rikku: Did you see their faces? They totally wet their pants!', 2, 'Airship', False),
    (0x9dd, 2, "Shinra: Hmmm... It's just a regular movie sphere.", 2, 'Airship', False),
    (0x9dd, 4, 'Brother: Wryd eh Spira es dryd machina?', 2, 'Airship', False),
    (0x9de, 4, 'Brother: Gullwings! Front and center!', 2, 'Airship', False),
    (0x9e9, 5, "Brother: So, uh... Let's give back that sphere...", 2, 'Airship', False),
    (0x9ec, 5, 'Yuna: The exercise will do us good.', 2, 'Airship', False),
    (0x9f6, 2, 'Brother: Ah, just some hitchhikers I picked up.', 2, 'Airship', False),
    (0xa02, 5, "Yuna: Who's Lenne?", 2, 'Airship', False),
    (0xa03, 3, 'Yuna: It must have been a dream.', 2, 'Airship', False),
    (0xa0f, 1, "Yuna: What's up?", 2, 'Airship', False),
    (0xa0f, 6, 'Brother: Uh... Aha! As leader, I order Yuna to decide!', 2, 'Airship', False),
    (0xa1b, 5, 'Brother: Where to?', 2, 'Airship', False),
    (0xa28, 1, "Rikku: Wow! They're pulling out all the stops!", 2, 'Mushroom Rock', False),
    (0xa28, 7, 'Shinra: Gullwings, GO! La-la-la-la-la!', 2, 'Mushroom Rock', False),
    (0xa35, 3, 'Nooj: Everyone, three cheers for the Gullwings!', 2, 'Mushroom Rock', False),
    (0xa35, 4, 'Nooj: So did you watch it?', 2, 'Mushroom Rock', False),
    (0xa36, 6, 'Nooj: that...thing... The colossus you saw is....', 2, 'Mushroom Rock', False),
    (0xa41, 1, "Rikku: Wow! They're pulling out all the stops!", 2, 'Bevelle (New Yevon)', False),
    (0xa4d, 5, 'Baralai: Gullwings, I welcome you.', 2, 'Bevelle (New Yevon)', False),
    (0xa4f, 1, 'Baralai: What you saw is Vegnagun, a weapon...', 2, 'Bevelle (New Yevon)', False),
    (0xa5a, 1, 'Barkeep: Intruders?', 2, 'Airship', False),
    (0xa5a, 6, "Leblanc: Who's on top now, Dullwings?", 2, 'Airship', False),
    (0xa5b, 1, 'Paine: She got us.', 2, 'Airship', False),
    (0xb47, 5, 'Oh, look, the Dullwings.', 2, 'Guadosalam', False),
    (0xa7f, 5, 'Datto: So you gave the sphere to the Youth League, ya?', 2, 'Besaid', False),
    (0xa7f, 7, 'Datto: So you returned the sphere to New Yevon?', 2, 'Besaid', False),
    (0xa80, 7, "Beclem: I am Beclem. I've been dispatched to...", 2, 'Besaid', False),
    (0xa83, 2, 'Beclem: The way you twaddled on before,...', 2, 'Besaid', False),
    (0xa84, 6, 'Beclem: Must your kind always prattle on about...', 2, 'Besaid', False),
    (0xa8c, 1, 'Dona: The Gullwings, was it not?', 2, 'Kilika', False),
    (0xa8c, 4, "Dona: If you're going to side with New Yevon,...", 2, 'Kilika', False),
    (0xd22, 5, 'Shelinda: Hello and welcome, Luca viewers.', 2, 'Luca', False),
    (0xd24, 5, 'Yuna: huh?', 2, 'Luca', False),
    (0xd28, 0, 'Paine: Not bad.', 2, 'Luca', False),
    (0xd2a, 6, 'Yuna: Hey, cut that out!', 2, 'Luca', False),
    (0xa9b, 4, '????: I see. Sorry to bother you...', 2, "Mi'ihen Highroad", False),
    (0xa98, 5, "????: You aren't Lady Yuna, by any chance?", 2, "Mi'ihen Highroad", False),
    (0xa9b, 2, 'Rikku: It went this way!', 2, "Mi'ihen Highroad", False),
    (0xaa6, 3, "Rikku: Maybe it's just me...but this is starting...", 2, "Mi'ihen Highroad", False),
    (0xaa7, 6, "Hey! Your friend's in hot water!", 2, "Mi'ihen Highroad", False),
    (0xad7, 3, 'Clasko: Hyah!', 2, "Mi'ihen Highroad", False),
    (0xad8, 7, 'Yuna: She looks happy.', 2, "Mi'ihen Highroad", False),
    (0xae3, 5, "Hey, it's the Gullwings!", 2, 'Mushroom Rock', False),
    (0xb15, 7, "Nooj: Oh. It's you.", 2, 'Mushroom Rock', False),
    (0xb18, 7, 'Rikku: Whoa, whoa, whoa! You know him?', 2, 'Mushroom Rock', False),
    (0xb09, 2, 'Elma: So...is it true that once the Gullwings...', 2, 'Mushroom Rock', False),
    (0x1da3, 6, 'Guys, where are you? (Crimson Record 7)', 2, 'Mushroom Rock', False),
    (0xae5, 2, "It's those sphere thieves, the Gullwings!", 2, 'Mushroom Rock', False),
    (0xaf0, 1, "Elma: Lady Yuna, say it ain't so.", 2, 'Mushroom Rock', False),
    (0xafc, 5, "Rikku: It's no good. This thing's not gonna budge.", 2, 'Mushroom Rock', False),
    (0xb17, 6, 'Nooj: I see the Gullwings have guts.', 2, 'Mushroom Rock', False),
    (0xb3b, 1, "Tobli: I am in big, big trouble! I'm supposed... (don't help tobli in Ch1)", 7, 'Moonflow', False),
    (0xb3c, 3, "Tobli: With the Gullwings in charge, we'll sell...", 2, 'Moonflow', False),
    (0xb3d, 2, "Tobli: And here it is! The promised... (don't help tobli in Ch1)", 7, 'Moonflow', False),
    (0xb9f, 5, "Cid: What, ya blind? Can't ya see I'm...", 2, 'Thunder Plains', False),
    (0xbab, 5, 'Hello, Gullwings. Good to shee yoo.', 2, 'Macalania Woods', False),
    (0xbad, 2, 'Thank yoo. If yoo find musishun, give...', 2, 'Macalania Woods', False),
    (0xbb8, 1, 'Bayra: What business do you have with me?', 2, 'Macalania Woods', False),
    (0xbb8, 4, 'Bayra: I must speak with my friends. It...', 2, 'Macalania Woods', False),
    (0xbb9, 0, 'Bayra: The spirits of my friends often become...', 2, 'Macalania Woods', False),
    (0xbc4, 5, 'Donga: Huh? What can I do for ye?', 2, 'Macalania Woods', False),
    (0xbc5, 1, 'Yuna: I have a favor to ask.', 2, 'Macalania Woods', False),
    (0xc03, 2, 'Clasko: Something tells me this is where...', 2, 'Calm Lands', False),
    (0xc03, 4, 'Lian: High Summoner Yuna, I am Lian Ronso.', 2, 'Calm Lands', False),
    (0xc0f, 6, 'Clasko: I was sure this would be the perfect spot,...', 2, 'Calm Lands', False),
    (0xc1c, 7, "Clasko: I can't raise anything without a chocobo!", 2, 'Calm Lands', False),
    (0xc28, 5, 'Kimahri: Kimahri sorry.', 2, 'Gagazete', False),
    (0xd09, 5, 'Yuna: Looks like business is booming.', 2, 'Zanarkand', False),
    (0xd16, 3, "Isaaru: It's a never-ending struggle.", 2, 'Zanarkand', False),
    (0xbf7, 3, "Nhadala: Oh, before you start digging, I'd really like...", 2, 'Bikinel Desert', False),
    (0xb22, 1, "That's weird. Where did we drop that thing?", 2, 'Djose', False),
    (0xb2e, 5, "Ormi: So that's where it was!", 2, 'Djose', False),
    (0xc8c, 5, 'Kimahri: Ronso youth filled with anger. Hate Guado.', 2, 'Gagazete', False),
    (0xc41, 5, "Rikku: You mean we're supposed to climb this?", 2, 'Gagazete', False),
    (0xc68, 5, "Yuna: Well, as long as we're here...", 2, 'Gagazete', False),
    (0xc74, 4, 'Yuna: Mission accomplished! We found ourselves a uniform.', 2, 'Gagazete', False),
    (0xa66, 6, "Brother: It's perfect!", 2, 'Airship', False),
    (0xb48, 3, "Rikku: Okie-dokie. Let's change.", 2, 'Guadosalam', False),
    (0xb54, 2, "Paine: We're not done yet. Where's the sphere?", 2, 'Guadosalam', False),
    (0xb54, 4, 'Nooj: Thank you, Leblanc.', 2, 'Guadosalam', False),
    (0xb60, 5, 'Ormi: The boss is a different person when that Nooj...', 2, 'Guadosalam', False),
    (0xb6d, 1, "Leblanc: I'm waiting.", 2, 'Guadosalam', False),
    (0xb6f, 0, 'Logos: The boss fell asleep again?', 2, 'Guadosalam', False),
    (0xb73, 2, 'Yuna: What does it do?', 2, 'Guadosalam', False),
    (0xb74, 1, 'Paine: Take it up with the boss.', 2, 'Guadosalam', False),
    (0xb7a, 3, "Brother: This is Brother! How's it going?", 2, 'Guadosalam', False),
    (0xb86, 1, "Rikku: Hey! This isn't the sphere they stole, is it?", 2, 'Guadosalam', False),
    (0x1dc9, 5, 'Did you say something? (crimson sphere #10)', 2, 'Guadosalam', False),
    (0xb86, 4, 'Logos: Only naughty girls would scrounge through...', 2, 'Guadosalam', False),
    (0xb93, 3, "Paine: I was wondering why they'd bother stealing...", 2, 'Guadosalam', False),
    (0xb94, 4, "Leblanc: W-Wait a second! I'll let you see what's in...", 2, 'Guadosalam', False),
    (0xb94, 7, 'Leblanc: That is the colossus Vegnagun.', 2, 'Guadosalam', False),
    (0xb96, 5, "Leblanc: So then I guess we're on the same side.", 2, 'Guadosalam', False),
    (0xb97, 1, 'Sin is gone. The Calm is here. I thought our peaceful...', 2, 'Guadosalam', False),
    (0xa73, 1, 'Leblanc: First things first. We are going to Bevelle.', 2, 'Airship', False),
    (0xa74, 1, "(before) Yuna: We're going to Bevelle. There should...", 2, 'Airship', False),
    (0xca5, 5, "Rikku: So how're we going to do this?", 2, 'Bevelle', False),
    (0xca6, 7, "It's those Youth League spies! We won't have you...", 2, 'Bevelle', False),
    (0xca7, 3, 'Oh, the high summoner! Please, forgive my rudeness!', 2, 'Bevelle (New Yevon)', False),
    (0xcbe, 5, 'Rikku: Wait. What are fiends doing in the temple?', 2, 'Bevelle', False),
    (0xccb, 1, 'Yuna: Watch the exit!', 2, 'Bevelle', False),
    (0xccb, 5, "Rikku: Hey! Wait! It's us, the Gullwings!", 2, 'Bevelle (New Yevon)', False),
    (0xcd7, 7, 'Rikku: That sphere with you-know-who in it.', 2, 'Bevelle', False),
    (0xcd8, 1, "There's a connection. Everything's connected.", 2, 'Bevelle', False),
    (0xce6, 7, "Paine: I'm going.", 2, 'Bevelle', False),
    (0xce7, 6, 'With so many things woven together...', 2, 'Bevelle', False),
    (0xcf0, 7, "Rikku: It's an aeon!", 2, 'Bevelle', False),
    (0xcf1, 3, 'Why is this happening? I wish you were here with me.', 2, 'Bevelle', False),
    (0xcfd, 1, 'Rikku: Nothing...', 2, 'Bevelle', False),
    (0xcfe, 1, 'Leblanc: I must report to Noojie-Woojie at once!', 2, 'Bevelle', False),
    (0xcfe, 5, "This isn't how it was supposed to be.", 2, 'Bevelle', False),
    (0xce4, 1, "Baralai: Waht's this? High Summoner Yuna?... (don't meet Baralai in Ch1)", 7, 'Bevelle', False),
    (0xeb2, 5, 'Buddy: Trouble. And I mean big time!', 3, 'Airship', False),
    (0xeb3, 2, 'Brother: Is it Gullwing time?', 3, 'Airship', False),
    (0xeb4, 1, 'Rikku: Hey, I got an idea!', 3, 'Airship', False),
    (0xeb5, 3, 'Runno up!', 3, 'Airship', False),
    (0x1123, 5, 'Buddy: Hm. No reports of fiend activity here.', 3, 'Luca', False),
    (0x1130, 1, "Shelinda: You can't go anywhere in Luca without...", 3, 'Luca', False),
    (0x1131, 3, "Shinra: It's elementary, really, once you get...", 3, 'Luca', False),
    (0x1149, 2, 'Shelinda: High Summoner Yuna!', 3, 'Luca', False),
    (0xf6e, 1, "It probably doesn't have anything to do with the temples...", 3, "Mi'ihen Highroad", False),
    (0xf6e, 5, "Okay, sounds like it's Mission Time!", 3, "Mi'ihen Highroad", False),
    (0xf7a, 5, "Thank you for all your help. Here's your reward, as promised.", 3, "Mi'ihen Highroad", False),
    (0xf87, 2, "Yaibal: No need for concern, Lady Yuna. Everything's under control.", 3, 'Mushroom Rock', False),
    (0xf88, 5, 'Lucil: As you are probably aware, we have not heard from...', 3, 'Mushroom Rock', False),
    (0xf89, 5, 'Yaibal: Forgive me, I...I have to return to my duties.', 3, 'Mushroom Rock (New Yevon)', False),
    (0xf93, 5, "Gippal: Hey, it's Cid's little girl!", 3, 'Djose', False),
    (0xfa0, 1, "Tobli: This won't do, won't do at all! We've finally put...", 3, 'Moonflow', False),
    (0xfac, 5, "Ormi: Leblanc, there's nothing to worry about.", 3, 'Guadosalam', False),
    (0xfb9, 1, 'Leblanc: Leave me alone.', 3, 'Guadosalam', False),
    (0xfc5, 5, 'Ormi: What if we showed her a sphere of Nooj?', 3, 'Guadosalam', False),
    (0xfd2, 3, 'Logos: Ormi shot this, not me.', 3, 'Guadosalam', False),
    (0xfd3, 3, "Rikku: It's Nooj!", 3, 'Guadosalam', False),
    (0xfde, 5, 'Yuna: Is this one from Bevelle, too?', 3, 'Guadosalam', False),
    (0xfdf, 1, "Bah! The only reason the war's dragging on...", 3, 'Guadosalam', False),
    (0xfe0, 5, "Maechen: I'm afraid not. After all, that sphere was...", 3, 'Guadosalam', False),
    (0xfeb, 5, 'Maechen: Oh, yes, that young man raised quite a few eyebrows...', 3, 'Guadosalam', False),
    (0x1d7e, 1, 'Kinoc: This is the final exercise.', 3, 'Guadosalam', False),
    (0x10f2, 4, 'Lian: Where does Lady Yuna think we should search for way...', 3, 'Thunder Plains', False),
    (0x10ff, 0, "Cid: At this rate, who knows when we'll... (told Cid 'not really' in Ch1)", 7, 'Thunder Plains', False),
    (0x1004, 3, 'Paine: Must be from Macalania Temple.', 3, 'Macalania Forest', False),
    (0x101d, 2, 'Wryd wys id?', 3, 'Macalania Forest', False),
    (0x101e, 0, "O'aka: Come on lad, I've come to give back the money...", 3, 'Macalania Forest', False),
    (0x101e, 6, "O'aka: Then I'll just have to start sellin' to fiends...", 3, 'Macalania Forest', False),
    (0x104f, 1, 'Nhadala: Boy, am I glad to see you!', 3, 'Bikanel Desert', False),
    (0x105b, 6, "Rikku: So where's this Marnela, anyway?", 3, 'Bikanel Desert', False),
    (0x110a, 5, 'Give us a straight answer! Where is Praetor Baralai?', 3, 'Bevelle (New Yevon)', False),
    (0x1029, 5, "Paine: This isn't a playground.", 3, 'Bevelle (New Yevon)', False),
    (0x1075, 1, "To be honest, I'd had enough. I wanted to blame them...", 3, 'Calm Lands', False),
    (0x1081, 3, 'Paine: Careful. Someone might answer.', 3, 'Calm Lands', False),
    (0x108d, 5, 'Kimahri: Yuna must leave.', 3, 'Gagazete', False),
    (0x109a, 1, 'Garik: Ronso hold anger no longer.', 3, 'Gagazete', False),
    (0x1117, 1, "Isaaru: I've heard that fiends have been appearing...", 3, 'Zanarkand', False),
    (0xed8, 2, "Lulu: They're coming from inside the temple.", 3, 'Besaid', False),
    (0xecb, 6, 'Shinra: Installing a CommSphere. You never know when...', 3, 'Besaid', False),
    (0xecd, 0, 'Shinra: How asinine.', 3, 'Besaid', False),
    (0xee4, 5, "Rikku: Yunie! Yunie! Something's up!", 3, 'Besaid', False),
    (0xee5, 6, 'Wakka: Hey! All we gotta do is stop the fiends, ya?', 3, 'Besaid', False),
    (0xef1, 6, 'Yuna: You want to see it burn that badly?', 3, 'Besaid', False),
    (0xefe, 2, "Wakka: Whatever's controlling the fiends must be down there.", 3, 'Besaid', False),
    (0xf0a, 2, "Yuna: No. Something's not right...", 3, 'Besaid', False),
    (0xf16, 6, 'Beclem: I see.', 3, 'Besaid', False),
    (0xf18, 7, 'Wakka: Fiends ever come out of the temple again,...', 3, 'Besaid', False),
    (0xf23, 1, 'Dona: My, my, my, my... What brings you here?', 3, 'Kilika', False),
    (0xf2f, 5, "Rikku: I think it's working!", 3, 'Kilika', False),
    (0xf3c, 2, "Yuna: 'Walk the treetops...'", 3, 'Kilika', False),
    (0xf55, 2, "Barthello: I'll be okay.", 3, 'Kilika', False),
    (0xf61, 6, 'Paine: An aeon?', 3, 'Kilika', False),
    (0xebf, 1, "Rikku: Mmm... I don't get it!", 3, 'Airship', False),
    (0xec0, 4, "Yuna: That's true, but they're connected somehow.", 3, 'Airship', False),
    (0xec2, 1, "Yuna: Well, we'll just have to charge him a little extra,...", 3, 'Airship', False),
    (0x1036, 2, 'Rikku: Was that...Gippal?', 3, 'Bevelle', False),
    (0x1042, 7, "Nooj: If you were on time, then I'd really start to worry.", 3, 'Bevelle', False),
    (0x1045, 1, 'Gippal: Who?', 3, 'Bevelle', False),
    (0x1047, 3, 'Baralai: Why did you shoot Gippal and me?', 3, 'Bevelle', False),
    (0x1049, 1, 'Nooj: I made him do it.', 3, 'Bevelle', False),
    (0x104a, 6, 'Paine: I saw Baralai escape.', 3, 'Bevelle', False),
    (0x104c, 6, 'Paine: No pressure, huh?', 3, 'Bevelle', False),
    (0x1d58, 5, 'Baralai: This is rough. (watch Crimson Sphere 1)', 3, 'Bevelle', False),
    (0x10a8, 7, "Yuna: Then that's our cue.", 3, 'Djose', False),
    (0x10b3, 2, 'Paine: Merged with Al Bhed machina.', 3, 'Djose', False),
    (0x10bf, 5, "Rikku: Another hole. I wonder what's down there.", 3, 'Djose', False),
    (0x10cc, 1, "Yuna: It's so bright.", 3, 'Djose', False),
    (0x10cc, 6, '????: Right here!', 3, 'Djose', False),
    (0x10da, 7, 'Nooj: Open your eyes!', 3, 'Djose', False),
    (0x10db, 0, 'Baralai: The end is not far now.', 3, 'Djose', False),
    (0x10dc, 4, "I didn't know what had happened.", 3, 'Djose', False),
    (0x10e5, 1, '(yuna falls to her knees before screaming)', 3, 'Djose', False),
    (0x10e5, 3, 'Yuna: Where are you?', 3, 'Djose', False),
    (0x10e5, 4, 'Yuna: Wait!', 3, 'Djose', False),
    (0x1394, 5, 'Brother: Wrad a namiav! I droukrd wa rad mosd oou.', 4, 'Airship', False),
    (0x1395, 6, 'Shinra: Yeah, the girl from the Songstress dressphere.', 4, 'Airship', False),
    (0x1396, 7, "Brother: Forget Lenne! Shuyin's the one who's wanting...", 4, 'Airship', False),
    (0x13a1, 3, 'Rikku: You met Shuyin, right?', 4, 'Airship', False),
    (0x13ae, 2, "(yuna turns around after Paine: They're old friends)", 4, 'Airship', False),
    (0x13b2, 1, 'But nothing leads to you.', 4, 'Airship', False),
    (0x13ba, 4, "Buddy: What about Yuna? Think she'll quit?", 4, 'Airship', False),
    (0x1d65, 1, 'Baralai: Ammo! (Crimson Report 2)', 4, 'Airship', False),
    (0x1d71, 5, "Baralai: What do you make of this Operation Mi'ihen? (Crimson Report 3)", 4, 'Airship', False),
    (0x1de2, 1, 'Wakka: Hey Yuna, how you been huh?', 4, 'Besaid', False),
    (0x1e84, 5, "Dona: Well, that's Kilika port for you.", 4, 'Kilika', False),
    (0x1f01, 7, "Yaibal: Actually, we've received some unconfirmed reports...", 4, 'Mushroom Rock', False),
    (0x2085, 2, "Maroda: Well, for one, I'm running reconnaisance...", 4, 'Bevelle', False),
    (0x13c6, 5, "Buddy: Looks like Nooj and Baralai still haven't...", 4, 'Airship', False),
    (0x13ca, 3, 'Rikku: I know! I know! I bet Tobli would help!', 4, 'Airship', False),
    (0x13cb, 2, 'Still, I will keep walking these roads.', 4, 'Airship', False),
    (0x13d3, 1, 'Paine: When you fought Sin, everyone came together and...', 4, 'Airship', False),
    (0x1dfb, 1, 'Yuna: Is it time?', 4, 'Besaid', False),
    (0x1e20, 5, "Beclem: Take my eyes off you for one minute and you're...", 4, 'Besaid', False),
    (0x1e91, 3, 'Barthello: But without Baralai...', 4, 'Kilika', False),
    (0x2247, 3, 'But I figure once blitzball season starts up...', 4, 'Luca', False),
    (0x1f65, 5, 'Al Bhed man talks to you (first dialog)', 4, 'Djose', False),
    (0x1fbd, 3, "Ormi: Yup, she just up and left. Went out lookin' for clues...", 4, 'Guadosalam', False),
    (0x202e, 0, 'Shinra: Yes, with my latest invention: The ChocoPorter.', 4, 'Thunder Plains', False),
    (0x2047, 1, 'Bayra: The fayth that protected Spira are not immune...', 4, 'Macalania Woods', False),
    (0x205f, 5, "O'aka: Hello! O'aka, at your service!", 4, 'Macalania Woods', False),
    (0x20ac, 3, 'Shinra: I wish I could play sometime too.', 4, 'Bevelle (New Yevon)', False),
    (0x20c3, 7, "Nhadala: But one thing...Lately there's been a pretty nasty fiend...", 4, 'Bikanel', False),
    (0x2173, 0, "Clasko: You're a good boy, aren't you?", 4, 'Calm Lands', False),
    (0x218b, 5, "Yuna: Hey, Kimahri! I'm going to be in a concert!", 4, 'Gagazete', False),
    (0x2209, 0, 'Tobli: Ahh! That really hit the spot!', 4, 'Gagazete', False),
    (0x220a, 3, 'Buddy: So, uh, where to, kids?', 4, 'Gagazete', False),
    (0x220b, 0, "O'aka: Welcome to O'aka's! (music note)", 4, 'Gagazete', False),
    (0x220d, 0, 'Isaaru: Maroda, may I have a word with you?', 4, 'Gagazete', False),
    (0x220d, 3, "Elma: I dunno.Why would I know what he's up to?", 4, 'Gagazete', False),
    (0x220d, 7, 'Maechen: Sacred Mt. Gagazete.', 4, 'Gagazete', False),
    (0x2210, 5, 'Nhadala: Listen, Cid.It might be cliche, but times...', 4, 'Gagazete', False),
    (0x2210, 7, 'Dona: My, my, my, my...', 4, 'Gagazete', False),
    (0x1ef5, 3, 'Rin: Lately a number of strange events...', 4, "Mi'ihen Highroad", False),
    (0x1ef6, 3, 'Rin: I have placed a number of modified comm...', 4, "Mi'ihen Highroad", False),
    (0x13e0, 3, "Hey, you! You haven't seen Tobli anywhere around...", 4, 'Moonflow', False),
    (0x13e2, 3, "You don't suppose he climbed into one a dem trees, do ya?", 4, 'Moonflow', False),
    (0x13ec, 3, "Tobli: Spectacularly spectacular! 'Twill be a yummy...", 4, 'Moonflow', False),
    (0x13ed, 4, "Advertising ish our shpeshalty.We'll get you your...", 4, 'Moonflow', False),
    (0x13f8, 5, "Buddy: We're over the Calm Lands now. We ready to go?", 4, 'Airship', False),
    (0x1405, 2, "Shinra: A project.I'm engineering a giant sphere screen...", 4, 'Airship', False),
    (0x1411, 5, 'Buddy: All the Hypello have been deployed.', 4, 'Airship', False),
    (0x1e39, 6, "Beclem: You've probably heard, but I've been called back...", 4, 'Besaid', False),
    (0x1e46, 1, 'Lulu: Shame on you, Yuna.', 4, 'Besaid', False),
    (0x1eb6, 5, 'Dona: Without you, the house seems so empty.', 4, 'Kilika', False),
    (0x1ecf, 5, 'Dona: The balloons are sure to reach the temple.', 4, 'Kilika', False),
    (0x1ee8, 6, 'Barthello: These are some balloons that Dona sent us.', 4, 'Kilika', False),
    (0x1f1a, 7, 'Yuna: Are you going to fight New Yevon?', 4, 'Mushroom Rock', False),
    (0x1f27, 3, 'Yuna: You could sneak out and come.', 4, 'Mushroom Rock', False),
    (0x1f97, 6, 'Elma: Ohh! I heard you the first time!', 4, 'Moonflow', False),
    (0x1fe3, 0, "Ormi: Back then we was workin' for those Yevon creeps.", 4, 'Guadosalam', False),
    (0x206c, 4, "O'aka: I swear on the O'aka name, I'd have...", 4, 'Macalania Woods', False),
    (0x2215, 3, "Isaaru: The Hypello told me the news.You're having a concert?", 4, 'Zanarkand', False),
    (0x2223, 0, "Isaaru: I wonder what I'm supposed to be protecting?", 4, 'Zanarkand', False),
    (0x141e, 1, "Barkeep: Rehearshal's shtarting.", 4, 'Airship', False),
    (0x141e, 3, "Yuna: It's almost time. Do you think people will show...", 4, 'Airship', False),
    (0x1437, 1, 'Hello, Gullwings.Good to shee yoo.', 4, 'Thunder Plains', False),
    (0x1443, 5, "Buddy: We're landing! If we cram any more people onboard...", 4, 'Thunder Plains', False),
    (0x1451, 3, 'Rikku: Hey, uh, the crowd is acting kinda funny.', 4, 'Airship', False),
    (0x1452, 1, 'The Yevonites are here too?', 4, 'Airship', False),
    (0x1453, 0, "Paine: Well, Yuna? You're the one wanted to...", 4, 'Airship', False),
    (0x1453, 5, 'Tobli: The spectators are making a spectacle!', 4, 'Airship', False),
    (0x1454, 4, 'Yuna: Ready?', 4, 'Airship', False),
    (0x145c, 5, 'Yuna: One thousand years ago, before the time of Sin...', 4, 'Airship', False),
    (0x145d, 5, 'Yuna: Believe with me:', 4, 'Airship', False),
    (0x1469, 2, "Yuna: I'm all right... I'm fine, really.", 4, 'Airship', False),
    (0x146a, 4, 'Paine: So the people we saw were Lenne...and Shuyin?', 4, 'Airship', False),
    (0x1475, 5, "Maechen: 'Twas a magnificent melody, Lady Yuna.", 4, 'Airship', False),
    (0x1477, 0, 'About a thousand years ago, Lenne was a popular songstress...', 4, 'Airship', False),
    (0x1482, 1, "Paine: So Shuyin was Lenne's lover.", 4, 'Airship', False),
    (0x1483, 6, 'Yuna: He never heard.The one person she wanted to tell...', 4, 'Airship', False),
    (0x148e, 5, "Leblanc: I've been hunting around since we last met,...", 4, 'Airship', False),
    (0x149b, 1, 'Shinra: What have we here?', 4, 'Airship', False),
    (0x149c, 2, 'Gippal: An invention like this could change the world.', 4, 'Airship', False),
    (0x149f, 2, "Leblanc: What a piece of junk! Forget it, I'll go...", 4, 'Airship', False),
    (0x14a0, 1, "Paine: We'll just have to jump into one of those holes.", 4, 'Airship', False),
    (0x271c, 5, "Rikku: Vegnagun's definitely bothering me, but...", 5, 'Airship', False),
    (0x2729, 1, 'Shinra: We know Vegnagun is in the deepest reaches...', 5, 'Airship', False),
    (0x2729, 7, 'Brother: Who cares! We just pick a hole and dive!', 5, 'Airship', False),
    (0x2780, 6, 'Barkeep: If yoo love her, tell her how you feel, yesh?', 5, 'Airship', False),
    (0x2782, 7, 'Barkeep: Thish is my darling, yesh?', 5, 'Airship', False),
    (0x2774, 1, "Buddy: Better keep your distance.Wouldn't wanna...", 5, 'Airship', False),
    (0x2775, 6, 'Buddy: And by some stroke of luck, we found this ship...', 5, 'Airship', False),
    (0x2777, 0, 'Buddy: Then, it appeared above us, out of nowhere: a single...', 5, 'Airship', False),
    (0x1d8a, 7, 'Gippal: Why are they killing eachother? (crimson sphere 5)', 5, 'Airship', False),
    (0x2735, 6, 'Buddy: Looks like Lulu finally had her baby.', 5, 'Airship', False),
    (0x1ab7, 2, "The monkeys can't do it alone.", 5, 'Zanarkand', False),
    (0x1acf, 1, 'Maechen: Although Vegnagun was constructed during the Machina War...', 5, 'Zanarkand', False),
    (0x1ad2, 4, "Rikku: Gramps! You're dead?", 5, 'Zanarkand', False),
    (0x1ad4, 5, 'Yuna: So people really are connected.', 5, 'Zanarkand', False),
    (0x1876, 5, 'Wakka: Hey!', 5, 'Besaid', False),
    (0x1883, 1, 'Rikku: Or, ra is so cuda!', 5, 'Besaid', False),
    (0x188f, 5, 'Beclem: Has Wakka settled on a name for his kid?', 5, 'Besaid', False),
    (0x189c, 2, "Wakka: I thought I'd go say goodbye to Beclem.", 5, 'Besaid', False),
    (0x189c, 7, 'Chappu: Hey, Wakka, remember that time...', 5, 'Besaid', False),
    (0x18a8, 5, 'That night, Wakka gathered everyone in the village...', 5, 'Besaid', False),
    (0x18a9, 7, 'Wakka: I chose a name. His name is Vidina.', 5, 'Besaid', False),
    (0x18ab, 6, "Wakka: But you know, in the end I'm just me.", 5, 'Besaid', False),
    (0x18ad, 3, "Rikku: They're in their own little world.", 5, 'Besaid', False),
    (0x18a0, 5, 'Wakka: Dryhg ouu. (Thank you)... (Episode concluded)', 7, 'Besaid', False),
    (0x18b6, 0, 'Dona: New Yevon this, Youth League that.', 5, 'Kilika', False),
    (0x18c1, 5, 'Paine: Songs are powerful.', 5, 'Kilika', False),
    (0x18c2, 4, 'Dona: Well, I...It seems to me you have forgotten...', 5, 'Kilika', False),
    (0x18c3, 6, "Yuna: That's so sweet.", 5, 'Kilika', False),
    (0x18c5, 1, 'Brother: Oooh! A Gullwings welcome bash?', 5, 'Kilika', False),
    (0x1b71, 1, 'Shelinda: The day that blitz freaks across Spira...', 5, 'Luca', False),
    (0x1b8a, 2, 'Yuna: Wherever I go, all over Spira is tied to my memories.', 5, 'Luca', False),
    (0x1ba4, 2, 'Rikku: You and someone you care about are connected...', 5, 'Luca', False),
    (0x1bbc, 2, 'Rin: I would like to talk about the recent string of incidents...', 5, "Mi'ihen Highroad", False),
    (0x1aa9, 1, "Gippal: Just got a transmission. Apparently the Guado...(Gippal's Sphere if you caught Rin)", 10, "Mi'ihen Highroad", False),
    (0x19af, 2, 'Elma: I went to your concert! It was spectacular!', 5, 'Mushroom Rock', False),
    (0x19e1, 3, 'Yaibal: And...I might not be talking to you right now.', 5, 'Mushroom Rock (New Yevon)', False),
    (0x19b2, 5, 'Lucil: Very well, all units take your positions!', 5, 'Mushroom Rock', False),
    (0x19bb, 6, "Elma: Awright, it's Elma time!", 5, 'Mushroom Rock', False),
    (0x19bd, 2, 'Lucil: Me? Lady Yuna, if I may?', 5, 'Mushroom Rock', False),
    (0x19bf, 7, 'Lucil: When the Calm arrived two years ago, it echoed...', 5, 'Mushroom Rock', False),
    (0x19c8, 1, 'Lucil: Yaibal, your unit will work with Machine Faction...', 5, 'Mushroom Rock', False),
    (0x19ee, 0, "Nooj: My body is half-machina.I'm kept alive beyond my time.", 5, 'Mushroom Rock', False),
    (0x19fa, 1, 'Wa did nasaancr on machina consdnucdion and buimd a supanwaapon!', 5, 'Djose', False),
    (0x19fb, 3, 'Paine: Tell him this:', 5, 'Djose', False),
    (0x1a13, 1, 'Tobli: Yunapalooza was a super smasheriffic success!', 5, 'Moonflow', False),
    (0x1a14, 7, 'Tobli: This is a dream.Mine, I mean!', 5, 'Moonflow', False),
    (0x18da, 6, 'It is as if this music delivered the Guado from our...', 5, 'Guadosalam', False),
    (0x18e8, 0, 'Rikku: What about you?', 5, 'Guadosalam', False),
    (0x18e8, 3, "Donga: Ah, quit yer bellyachin'! Ye'd make a fine leader.", 5, 'Guadosalam', False),
    (0x18f4, 2, 'Tromell: This was to be the final resting place for the...', 5, 'Guadosalam', False),
    (0x1900, 3, 'I knew it! Lian and Ayde told me about you!', 5, 'Guadosalam', False),
    (0x190c, 5, "Baralai: The Crimson Squad is no more. Maester Kinoc is... (Yevon's Secret sphere)", 5, 'Guadosalam', False),
    (0x1a38, 6, 'Shinra: Sphere waves scattered udring the concert caused...', 5, 'Thunder Plains', False),
    (0x1a51, 7, 'Rikku: Howdy? What howdy? What the heck are you doing?', 5, 'Thunder Plains', False),
    (0x1a54, 4, 'Yuna: If only I could have talked like this with my father...', 5, 'Thunder Plains', False),
    (0x278d, 1, 'Cid: Shameful, how they gussied this baby up!', 5, 'Thunder Plains', False),
    (0x279a, 1, 'Cid: Do whad oou wand.', 5, 'Thunder Plains', False),
    (0x1a77, 1, "O'aka: How dare ye drag yer sorry bum back here!", 5, 'Macalania Woods', False),
    (0x1a6a, 5, '(immediately on spring-1 scene)', 5, 'Macalania Woods', False),
    (0x1a6b, 2, "I'm not ready to call this just a memory. Not yet.", 5, 'Macalania Woods', False),
    (0x1964, 3, "Nhadala: We've got a prickly situation. Fiends are...", 5, 'Bikanel', False),
    (0x1973, 3, "Benzo: Find the Gatekeepers before Marnela's strength...", 5, 'Bikanel', False),
    (0x1aeb, 0, 'Maroda: He goes around playing superhero and leaves...', 5, 'Bevelle', False),
    (0x1ae8, 3, "Pacce: Hey Maroda, who you talkin' about?", 5, 'Bevelle (New Yevon)', False),
    (0x1af4, 4, 'Taro: We found it all by ourselves!', 5, 'Bevelle', False),
    (0x1b01, 1, 'Rikku: Farplane!', 5, 'Bevelle', False),
    (0x1d97, 2, 'What did you see? (Crimson Sphere 6)', 5, 'Bevelle', False),
    (0x1b0d, 1, 'Paine: Maester Kinoc!', 5, 'Bevelle', False),
    (0x1db0, 1, "Nooj: I'm glad you're alright. (Crimson Sphere 8)", 5, 'Bevelle', False),
    (0x1a83, 7, 'Tobli: Yup-yup! I can taste it in the air!', 5, 'Calm Lands', False),
    (0x1919, 6, 'Garik: Elder, what path should Ronso walk?', 5, 'Gagazete', False),
    (0x1926, 1, 'Kimahri: Kimahri must lead way to Ronso future.', 5, 'Gagazete', False),
    (0x1927, 6, 'Kimahri: Lian and Ayde enjoy seeing vast Spira?', 5, 'Gagazete', False),
    (0x1933, 3, 'Kimahri: Garik not think for himself!', 5, 'Gagazete', False),
    (0x193e, 5, 'Garik: Maybe it needs horn?', 5, 'Gagazete', False),
    (0x193f, 2, 'Garik: Honor to Ronso! Honor to mountain!', 5, 'Gagazete', False),
    (0x1989, 5, 'Benzo: The Cactuar Nation will be safe from fiends now.', 5, 'Bikanel', False),
    (0x198a, 2, "Rikku: Now a fiend's attacking the camp!", 5, 'Bikanel', False),
    (0x1997, 6, "Nhadala: It's all relative. This is nothing compared to...", 5, 'Bikanel', False),
    (0x19a2, 5, 'Yuna: So...I guess Marnela is gone.', 5, 'Bikanel', False),
    (0x1b32, 6, 'Paine: Time to face my past. Come on.', 5, 'Mushroom Rock', False),
    (0x1b3f, 1, "Rikku: Something's coming!", 5, 'Mushroom Rock', False),
    (0x1b41, 2, 'Shuyin: I wanted to rest forever, but the pyreflies...', 5, 'Mushroom Rock', False),
    (0x1b4b, 6, 'Shuyin: This is our story, Lene.', 5, 'Mushroom Rock', False),
    (0x1b58, 2, 'Yuna: Snap out of it!', 5, 'Mushroom Rock', False),
    (0x1b58, 6, 'Paine: When he died a thousand years ago, his feelings...', 5, 'Mushroom Rock', False),
    (0x1b59, 7, "Paine: You'll pay! (a second before she says it)", 5, 'Mushroom Rock', False),
    (0x1b64, 7, "Paine: Two years ago, the guys encountered Shuyin's...", 5, 'Mushroom Rock', False),
    (0x1a9d, 5, "They make a cute couple, don't you think?", 5, 'Calm Lands', False),
    (0x1a08, 2, 'Rikku: So...who taught you to speak Al Bhed?', 5, 'Djose', False),
    (0x1a0a, 0, "Paine: What I'm trying to say is that running...(just before this line)", 5, 'Djose', False),
    (0x275b, 1, 'Buddy: A special bonus for the Gullwings!', 5, 'Airship', False),
    (0x1b1a, 1, 'Paine: Trema is the founder of New Yevon. (Floor 60)', 5, 'Bevelle', False),
    (0x1b26, 1, "Paine: So. You're Trema. (Floor 100)", 5, 'Bevelle', False),
    (0x1b28, 7, 'Yuna: I realize that losing my past would mean losing...', 5, 'Bevelle', False),
    (0x2742, 5, 'Brother: Your friendly neigh... Heh?', 5, 'Airship', False),
    (0x2743, 1, 'Brother: Surging Flapping Neighboring Gullwings, attack!!', 5, 'Airship', False),
    (0x27cb, 7, 'We wanted to at least warn someone... but instead...', 5, 'Farplane', False),
    (0x27cd, 3, 'Yuna: I can handle a shadow.', 5, 'Farplane', False),
    (0x27d8, 4, "Logos: Because the boss never goes against Lord Nooj's...", 5, 'Farplane', False),
    (0x27d9, 7, "Leblanc: You do that, love. And don't forget to stress...", 5, 'Farplane', False),
    (0x2768, 0, 'Shinra: The more I study it, the more fascinating it gets.', 5, 'Airship', False),
    (0x27a8, 1, 'Buddy: Cid?', 5, 'Airship', False),
    (0x27b3, 0, "Cid: I don't know what this sphere hunter business is...", 5, 'Airship', False),
    (0x27b6, 0, 'I was born in Bevelle. I grew up in Besaid...', 5, 'Airship', False),
    (0x27c0, 2, 'Yuna: Yeah. Next time will be your story.', 5, 'Airship', False),
    (0x27e5, 0, 'Gippal: I could use...a nap.', 5, 'Farplane', False),
    (0x27e6, 7, "Yuna: Think about it. You know you won't be able to fight...", 5, 'Farplane', False),
    (0x27f1, 2, "Gippal: Any ideas, Dr. P? (Paine's sphere)", 5, 'Farplane', False),
    (0x27f3, 0, 'Paine: What happened to that Paine, I wonder.', 5, 'Farplane', False),
    (0x280a, 1, "Yuna: It's moving!", 5, 'Farplane', False),
    (0x2816, 7, "Nooj: I have a plan. Can't call it a smart one, though.", 5, 'Farplane', False),
    (0x2818, 6, "(When everyone reacts to Yuna saying 'It sucks.')", 5, 'Farplane', False),
    (0x281a, 1, "(right after screen changes when you hear 'forgive us.')", 5, 'Farplane', False),
    (0x281c, 1, 'Paine: Light?', 5, 'Farplane', False),
    (0x281d, 1, 'Leblanc: And I never was the wait-like-a-good-girl type...', 5, 'Farplane', False),
    (0x2820, 2, 'Yuna: If we all attack at once, we can do this!', 5, 'Farplane', False),
    (0x2830, 0, 'Leblanc: You want to get the heel?', 5, 'Farplane', False),
    (0x283c, 2, "Leblanc: I'll let you have this one. I'm gonna go cheer... (98.6%)", 5, 'Farplane', False),
    (0x2848, 7, 'Yuna: The Gullwings are on it!', 5, 'Farplane', False),
    (0x2856, 1, 'Yuna: This is it, everyone! Stay focused!', 5, 'Farplane', False),
    (0x2856, 7, '(a split second after the last line)', 5, 'Farplane', False),
    (0x2857, 2, "Yuna: There's something I must tell you. Words left unspoken...", 5, 'Farplane', False),
    (0x2858, 4, 'Shuyin: You are not Lenne!', 5, 'Farplane', False),
    (0x2859, 3, 'Shuyin: A thousand years, and this moment is all we get?', 5, 'Farplane', False),
    (0x285a, 3, "Lenne: Let's go. I have a new song for you.", 5, 'Farplane', False),
    (0x2861, 5, "*screen fades white... (don't do 4 whistles ch3)", 7, 'Farplane', False),
    (0x2862, 0, "Yuna: But you know, I'm not worried anymore. (don't do 4 whistles ch3)", 7, 'Farplane', False),
    (0x268, 0, 'Slept in airship cabin Chapter 1', 1, 'Airship', True),
    (0x268, 1, 'Slept in airship cabin Chapter 2', 2, 'Airship', True),
    (0x268, 2, 'Slept in airship cabin Chapter 3', 3, 'Airship', True),
    (0x268, 3, 'Slept in airship cabin Chapter 4', 4, 'Airship', True),
    (0x268, 4, 'Slept in airship cabin Chapter 5', 5, 'Airship', True),
    (0x489, 5, "Saw HQ form Kilika man's camera Chapter 1", 1, 'Kilika', True),
    (0x489, 6, "Saw HQ from Kilika man's camera Chapter 3", 3, 'Kilika', True),
    (0x439, 0, "Spoke to al bhed girl with 3 machina on mi'ihen", 3, "Mi'ihen", False),
    (0x231, 6, 'Let Clasko join airship', 2, "Mi'ihen", True),
    (0x388, 7, "Allowed O'aka to lay low on your ship", 1, 'Macalania', True),
    (0xc60, 0, "Told Cid 'You bet I do!' in Zanarkand", 1, 'Zanarkand', True),
    (0x439, 2, 'Machina destroying mission complete', 3, "Mi'ihen", True),
    (0x317, 0, "Shinra spotted installing sphere in mi'ihen", 3, "Mi'ihen", True),
    (0x318, 5, "Shinra dropped a comm sphere on mi'ihen road N", 3, "Mi'ihen", True),
    (0x234, 3, 'Shinra seen placing a comm sphere at mushroom rock, but then he moves it', 3, 'Mushroom Rock', True),
    (0xca1, 6, 'Shinra seen placing a comm sphere at moonflow', 3, 'Moonflow', True),
    (0xca1, 7, 'Shinra seen placing a comm sphere at guadosalam', 3, 'Guadosalam', True),
    (0xca2, 0, 'Shinra seen placing a comm sphere at thunder plains', 3, 'Thunder Plains', True),
    (0xca2, 1, 'Shinra seen placing a comm sphere at macalania', 3, 'Macalania', True),
    (0xca2, 7, 'Shinra seen placing a comm sphere at macalania agency', 3, 'Macalania', True),
    (0xca3, 1, 'Automatic install on scene of hover driving to cactuar nation', 3, 'Bikanel', True),
    (0xca2, 0, 'Automatic install when visiting bridge to Gagazet', 3, 'Gagazet', True),
    (0xca2, 2, 'Shinra seen placing a comm sphere at bevelle', 3, 'Bevelle', True),
    (0x317, 3, 'Shinra seen placing a comm sphere at Calm Land Agency', 3, 'Calm Lands', True),
    (0x318, 7, 'Shinra seen placing a comm sphere in chocobo ranch', 3, 'Calm Lands', True),
    (0xca2, 5, 'Shinra seen placing a comm sphere in Gagazet', 3, 'Gagazet', True),
    (0xca2, 6, 'Shinra seen placing a comm sphere in Zanarkand', 3, 'Zanarkand', True),
    (0xca1, 0, 'Shinra scene placing a comm sphere in Besaid', 3, 'Besaid', True),
    (0xca1, 1, 'Shinra seen placing a comm sphere in Djose Temple', 3, 'Djose Temple', True),
    (0xf88, 1, 'Four whistles heard in Farplane', 5, 'Farplane', True),
]

